controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authenticate:
    path: /authenticate
    methods: ['POST']

api_villes:
    path: /api/villes
    methods: ['GET']
    controller: App\Controller\VilleController::getVillesAction